### ISSUE TITLE
CI/CD for fastpost

### ISSUE THREAD

**Issue by R1AACR** [kosc/fastpost#11]
I think we need a CI/CD like Travis, for this project.
It will give us an automatic tests and deploy directly to fastpost.hotkosc.ru after each push to master without any acting upon it.
But this will make you follow a feature branch workflow in this repository.
I can deploy and manage it if it would be needed.

**Comment by kosc** [comment]
OK. let's do that.

**Comment by R1AACR** [comment]
Closed in #18
